/**
 * GAMEPLAY CONFIG - Configuration generale et constantes du jeu
 * @version 1.0.0
 */

// Configuration generale du jeu
const CONFIG = {
  ROOM_WIDTH: 3000,
  ROOM_HEIGHT: 2400,
  WALL_THICKNESS: 40,
  PLAYER_SPEED: 5,
  PLAYER_SIZE: 20,
  ZOMBIE_SIZE: 25,
  ZOMBIE_SPAWN_INTERVAL: 1000,
  MAX_ZOMBIES: 50,
  BULLET_SPEED: 10,
  BULLET_DAMAGE: 34,
  BULLET_SIZE: 5,
  PLAYER_MAX_HEALTH: 100,
  POWERUP_SPAWN_INTERVAL: 15000,
  POWERUP_SIZE: 15,
  ZOMBIES_PER_ROOM: 25,
  LOOT_SIZE: 10,
  DOOR_WIDTH: 120,
  ROOMS_PER_RUN: 3
};

// Constantes d'inactivite
const INACTIVITY_TIMEOUT = 120000;
const HEARTBEAT_CHECK_INTERVAL = 15000;

// Constantes gameplay (magic numbers extraits)
const GAMEPLAY_CONSTANTS = {
  GAME_LOOP_TIMEOUT: 5000,
  COMBO_TIMEOUT: 5000,
  REGENERATION_TICK_INTERVAL: 1000,
  AUTO_TURRET_BASE_COOLDOWN: 600,
  AUTO_TURRET_RANGE: 500,
  SLOW_FRAME_WARNING_THRESHOLD: 33,
  FAILED_DEATH_QUEUE_MAX_SIZE: 100,
  SURVIVAL_TIME_MULTIPLIER: 1000
};

module.exports = {
  CONFIG,
  INACTIVITY_TIMEOUT,
  HEARTBEAT_CHECK_INTERVAL,
  GAMEPLAY_CONSTANTS
};
