#!/bin/sh
commit_msg=$(cat "$1")
pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?!?: .+'
if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "commit-msg: format invalide. Attendu: type(scope): message"
  exit 1
fi
